version: 2
jobs:
  build:
    
    working_directory: ~/repo

    docker:
      - image: debian:jessie-backports

    steps:
      - run: apt-get update -qq && apt-get install -qqy -t jessie-backports wget openjdk-8-jdk-headless git zip
      - checkout
      - run: bash .circleci/setup.sh

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/http-request-*.jar
